version: '3.9'
services:
  vertice-postgres-dev:
    image: postgres:13.2
    volumes:
      - ../../.volumes/vertice-db/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vertice
      - POSTGRES_PASSWORD=vertice
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=cryptobot
    ports:
      - "5432:5432"
